Repository scylladb/python-driver, pull requests merged in 2020-07, with the labels that each got.

#36 Added multiversion support
  .github/workflows/pages.yml
  docs/Makefile
  docs/_utils/deploy.sh
  docs/_utils/preview
  docs/_utils/preview.py
  docs/_utils/preview.sh
  docs/_utils/redirect.html
  docs/conf.py
  docs/docs-requirements.txt
Labels: docs

#42 Updated theme 0.1.7
  docs/docs-requirements.txt
Labels: docs

#44 Remove DSE pages, add Scylla Cloud Page
  docs/conf.py
  docs/index.rst
  docs/scylla_cloud.rst
Labels: docs

#53 fix the link to the documentions in README.rst
  README.rst
Labels: bug, docs

#56 pool: fix cluster shutdown RuntimeError on short lived sessions
  cassandra/pool.py
Labels: bug

#46 Fix integration tests
  .travis.yml
  ci/run_integration_test.sh
  test-requirements.txt
  tests/integration/__init__.py
  tests/integration/standard/test_authentication_misconfiguration.py
  tests/integration/standard/test_client_warnings.py
  tests/integration/standard/test_cluster.py
  tests/integration/standard/test_custom_payload.py
  tests/integration/standard/test_custom_protocol_handler.py
  tests/integration/standard/test_metadata.py
  tests/integration/standard/test_prepared_statements.py
  tests/integration/standard/test_query.py
  tests/integration/standard/test_shard_aware.py
  tests/integration/standard/test_types.py
  tests/integration/standard/test_udts.py
Labels: bug

#59 Adding python3.9 wheels release
  .travis.yml
Labels: enhancement
